"use client"

import { ToastContainer, Zoom } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/ThemeProvider"
import { ClerkProvider } from '@clerk/nextjs'
import { SpeedInsights } from "@vercel/speed-insights/next"

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

import { Kalam } from "next/font/google"; // Import Kalam

const kalam = Kalam({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-kalam",
});

// export const metadata: Metadata = {
//   title: "Xcal",
//   description: "Generated by create next app",
// };

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <ClerkProvider>
         <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} ${kalam.variable} antialiased`}>
               <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange>


                  {children}
                  <SpeedInsights />
                  <ToastContainer
                     position="top-center"
                     autoClose={5000}
                     hideProgressBar={false}
                     newestOnTop={true}
                     rtl={false}
                     pauseOnHover
                     transition={Zoom}
                  />

               </ThemeProvider>


            </body>
         </html>

      </ClerkProvider>
   );
}
